export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS_REQUEST = 'LOGIN_SUCCESS_REQUEST'
export const LOGIN_ERROR_REQUEST = 'LOGIN_ERROR_REQUEST'

export const SHOW_LOADING_LOGIN = 'SHOW_LOADING_LOGIN'
export const SHOW_LOADING_LOGIN_FULL_PAGE = 'SHOW_LOADING_LOGIN_FULL_PAGE'
