export const CATEGORY_SELECT_REQUEST = 'CATEGORY_SELECT_REQUEST';
export const CATEGORY_SELECT_SUCCESS_REQUEST = 'CATEGORY_SELECT_SUCCESS_REQUEST';
export const CATEGORY_SELECT_ERROR = 'CATEGORY_SELECT_ERROR';

