export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS_REQUEST = 'CATEGORY_CREATE_SUCCESS_REQUEST';
export const CATEGORY_CREATE_ERROR = 'CATEGORY_CREATE_ERROR';

