export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS_REQUEST = 'CATEGORY_CREATE_SUCCESS_REQUEST';
export const CATEGORY_CREATE_ERROR = 'CATEGORY_CREATE_ERROR';

export const CATEGORY_SELECT_REQUEST = 'CATEGORY_SELECT_REQUEST';
export const CATEGORY_SELECT_SUCCESS_REQUEST = 'CATEGORY_SELECT_SUCCESS_REQUEST';
export const CATEGORY_SELECT_ERROR = 'CATEGORY_SELECT_ERROR';












export const SHOW_CATEGORY_MODAL = 'SHOW_CATEGORY_MODAL';
