export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS_REQUEST = 'CATEGORY_CREATE_SUCCESS_REQUEST'
export const CATEGORY_CREATE_ERROR = 'CATEGORY_CREATE_ERROR'

export const CATEGORY_SELECT_REQUEST = 'CATEGORY_SELECT_REQUEST'
export const CATEGORY_SELECT_SUCCESS_REQUEST = 'CATEGORY_SELECT_SUCCESS_REQUEST'
export const CATEGORY_SELECT_ERROR = 'CATEGORY_SELECT_ERROR'

export const SHOW_CATEGORY_MODAL = 'SHOW_CATEGORY_MODAL'
export const SHOW_CATEGORY_DELETE_MODAL_OPEN = 'SHOW_CATEGORY_DELETE_MODAL_OPEN'
export const SHOW_CATEGORY_EDIT_MODAL_OPEN = 'SHOW_CATEGORY_EDIT_MODAL_OPEN'
export const CATEGORY_EDIT_DATA = 'CATEGORY_EDIT_DATA'

export const CATEGORY_LIST_DELETE = 'CATEGORY_LIST_DELETE'
export const CATEGORY_LIST_DELETE_ADD = 'CATEGORY_LIST_DELETE_ADD'
export const CATEGORY_LIST_DELETE_CLEAR = 'CATEGORY_LIST_DELETE_CLEAR'



export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS_REQUEST = 'CATEGORY_DELETE_SUCCESS_REQUEST'
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR'



export const CATEGORY_EDIT_REQUEST = 'CATEGORY_EDIT_REQUEST'
export const CATEGORY_EDIT_SUCCESS_REQUEST = 'CATEGORY_EDIT_SUCCESS_REQUEST'
export const CATEGORY_EDIT_ERROR = 'CATEGORY_EDIT_ERROR'