export const USER_FETCH_SUCCEEDED = 'USER_ACTION_USER_FETCH_SUCCEEDED';
export const USER_FETCH_REQUESTED = 'USER_ACTION_USER_FETCH_REQUESTED';
export const USER_FETCH_FAILED = 'USER_ACTION_USER_FETCH_FAILED';